name = "ABM4OSN"
uuid = "1db57389-35cd-48e7-8881-e022b7095b51"
authors = ["Patrick Halbach", "Johannes Nakayama"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
